datagrid:
    jobs-grid-dashboard:
        source:
            type: orm
            acl_resource: oro_jobs
            query:
                select:
                    - j.id 
                    - j.args 
                    - j.state
                    - j.createdAt
                    - channel.name as channelName
                    - channel.type as channelType
                from:
                    - { table: JMSJobQueueBundle:Job , alias: j }
                join:
                    inner:
                        -
                            join: Oro\Bundle\IntegrationBundle\Entity\Channel
                            alias: channel
                            conditionType: WITH
                            condition: "substring(j.args, 16,1) = channel.id"
                where:
                    and:
                        - j.originalJob IS NULL
        columns:
            channelName:
                label: tfone.dashboard.datagrid.channelName
                type: twig
                template: TfoneJobQueueWidgetBundle:Datagrid:Column/channelName.html.twig
                frontend_type: html
            channelType:
                label: tfone.dashboard.datagrid.channelType
            state:
                label: tfone.dashboard.datagrid.status
                type: twig
                template: TfoneJobQueueWidgetBundle:Datagrid:Column/status.html.twig
                frontend_type: html
            createdAt:
                label: oro.cron.header.created
                frontend_type: datetime
        sorters:
            columns:
                state:               { data_name: j.state }
                createdAt:           { data_name: j.createdAt }
            default:
                createdAt: DESC
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
            entityHint: job
