datagrid:
    jobs-grid-dashboard:
        source:
            type: orm
            acl_resource: oro_jobs
            query:
                select:
                    - j.id
                    - j.state
                    - j.command
                    - j.createdAt
                    - j.id as identifier
                    ##j.id as identifier tmp solution for getting id of the job into the view
                from:
                    - { table: JMSJobQueueBundle:Job , alias: j }
                where:
                    and:
                        - j.originalJob IS NULL
        columns:
            command:
                label: tfone.dashboard.datagrid.command
                type: twig
                template: TfoneJobQueueWidgetBundle:Datagrid:Column/command.html.twig
                frontend_type: html
            state:
                label: tfone.dashboard.datagrid.state
                type: twig
                template: TfoneJobQueueWidgetBundle:Datagrid:Column/state.html.twig
                frontend_type: html
            createdAt:
                label: tfone.dashboard.datagrid.created
                frontend_type: datetime
            identifier:
                label: null   
                type: twig
                template: TfoneJobQueueWidgetBundle:Datagrid:Column/viewjob.html.twig
                frontend_type: html
        sorters:
            columns:
                state:               { data_name: j.state }
            default:
                state: ASC
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_cron_job_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_cron_job_view
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
            entityHint: job
